# Application Name
spring.application.name=movie-ticket-booking

# MySQL Database Connection (FIXED)
spring.datasource.url=${postgresql://movie_db_dfhx_user:lIe1WSmxMG4pvsrwJuhT2tWfwxHlOIw5@dpg-d7ad0a0gjchc73fnjdt0-a/movie_db_dfhx}
spring.datasource.username=${movie_db_dfhx_user}
spring.datasource.password=${lIe1WSmxMG4pvsrwJuhT2tWfwxHlOIw5}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080

# Security (for testing)
spring.security.user.name=admin
spring.security.user.password=admin123
